[package]
name = "hosts-dns-forwarder"
version = "0.1.0"
edition = "2021"

[dependencies]
trust-dns-proto = "0.23"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "time", "fs"] }
anyhow = "1"
url = ">=2.4, <2.5"
